"""empty message

Revision ID: b885d203550f
Revises: 
Create Date: 2018-08-07 02:51:54.912060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b885d203550f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('administrator', sa.Column('date', sa.DateTime(), nullable=True))
    op.add_column('administrator', sa.Column('userid', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_administrator_email'), 'administrator', ['email'], unique=True)
    op.create_index(op.f('ix_administrator_username'), 'administrator', ['username'], unique=True)
    op.drop_column('administrator', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('administrator', sa.Column('id', sa.INTEGER(), nullable=False))
    op.drop_index(op.f('ix_administrator_username'), table_name='administrator')
    op.drop_index(op.f('ix_administrator_email'), table_name='administrator')
    op.drop_column('administrator', 'userid')
    op.drop_column('administrator', 'date')
    # ### end Alembic commands ###
